In [1]:
import pandas as pd
import numpy as np

In [2]:
PATH_DATA = '../mydata/'

## Get data

In [3]:
df_food = pd.read_csv(PATH_DATA+'food_delivery_datasets.csv')

In [5]:
df_food.head()
# df_csv.head(10)

,order_id,voucher_amount,date_time,eta_seconds,food_price,cust_id,rating,delivery_fee,resto_id,status,random_id
0,FOOD-10455,0,2018-08-12T20:35:08.001006,1800,18900,1089034,5.0,4000,742638033,Completed,0.511149
1,FOOD-10985,0,2018-09-23T17:44:12.243273,2173,149000,180146,5.0,11000,742767245,Completed,0.832936
2,FOOD-10911,0,2018-09-19T18:08:09.387991,1418,43800,366528,NaN,9000,742618303,Completed,0.828026
3,FOOD-10932,0,2018-09-21T01:24:35.272499,1903,39900,511038,5.0,14000,742541172,Completed,0.239377
4,FOOD-10961,0,2018-09-22T17:57:45.523161,1716,77700,1220358,NaN,4000,742604875,Completed,0.995587

In [6]:
group_typ = df_food.groupby(['cust_id'])

In [10]:
measure_dict = {'food_price': [np.mean, np.std]}

{'food_price': [<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>,
  <function numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)>]}

In [13]:
# group_typ['food_price'].mean()
# group_typ.agg(measure_dict)

In [14]:
rename_dict = {'voucher_amount': 'voucher_amt', 'eta_seconds': 'time_arrival'}

In [15]:
df_food.rename(columns=rename_dict)

,order_id,voucher_amt,date_time,time_arrival,food_price,cust_id,rating,delivery_fee,resto_id,status,random_id
0,FOOD-10455,0,2018-08-12T20:35:08.001006,1800,18900,1089034,5.0,4000,742638033,Completed,0.511149
1,FOOD-10985,0,2018-09-23T17:44:12.243273,2173,149000,180146,5.0,11000,742767245,Completed,0.832936
2,FOOD-10911,0,2018-09-19T18:08:09.387991,1418,43800,366528,NaN,9000,742618303,Completed,0.828026
3,FOOD-10932,0,2018-09-21T01:24:35.272499,1903,39900,511038,5.0,14000,742541172,Completed,0.239377
4,FOOD-10961,0,2018-09-22T17:57:45.523161,1716,77700,1220358,NaN,4000,742604875,Completed,0.995587
5,FOOD-10004,0,2018-07-01T14:24:06.719768,2344,138800,466885,5.0,10000,225641128,Completed,0.341921
6,FOOD-10953,0,2018-09-22T13:37:33.712943,1449,58700,463180,5.0,4000,742550960,Completed,0.232322
7,FOOD-10464,0,2018-08-13T20:37:56.355441,2041,74200,1472725,5.0,13000,742534099,Completed,0.162013
8,FOOD-10342,10000,2018-08-03T13:58:54.286742,1265,37500,304856,5.0,0,742670531,Completed,0.373261
9,FOOD-10942,0,2018-09-21T22:51:22.145050,1580,80800,511038,NaN,11000,742541172,Completed,0.217071
10,FOOD-10386,0,2018-08-06T14:57:55.985171,2673,437800,1163202,5.0,12000,742554110,Completed,0.485939
11,FOOD-10909,5000,2018-09-19T13:35:35.612145,2149,79200,1089034,5.0,2000,742594125,Completed,0.438527
12,FOOD-10008,3000,2018-07-01T17:27:58.151546,1416,56700,1347550,5.0,7000,742544599,Completed,0.799689
13,FOOD-10141,0,2018-07-14T17:57:45.108952,2514,339800,366528,5.0,13000,742538990,Completed,0.436648
14,FOOD-10671,0,2018-09-02T15:26:19.725547,1939,45600,1319474,5.0,4000,742630797,Completed,0.900757
15,FOOD-10436,0,2018-08-11T18:20:00.835032,1760,74800,1319474,5.0,10000,742531018,Completed,0.049066
16,FOOD-10978,4000,2018-09-23T14:18:37.731404,1204,33100,1163202,5.0,0,742531705,Completed,0.596303
17,FOOD-10594,0,2018-08-26T17:48:59.683373,603,56100,366721,5.0,8000,742531121,Completed,0.785234
18,FOOD-10360,0,2018-08-04T16:08:26.196958,983,64800,1191779,NaN,9000,742618679,Completed,0.516239
19,FOOD-10665,0,2018-09-02T01:48:45.074177,1930,49100,316834,5.0,12000,742676756,Completed,0.476840
20,FOOD-10888,0,2018-09-18T11:14:27.408029,632,44600,1383625,NaN,10000,742756630,Cancelled,0.208880
21,FOOD-10243,0,2018-07-24T11:05:19.481372,1353,131000,472466,5.0,5000,742531805,Completed,0.259309
22,FOOD-10394,0,2018-08-07T14:48:42.559078,331,29700,1364703,NaN,16000,742656058,Cancelled,0.640676
23,FOOD-10216,0,2018-07-21T23:41:55.508813,2016,51000,380092,5.0,12000,742702327,Completed,0.302137
24,FOOD-10032,0,2018-07-04T13:05:10.988492,1522,34900,1089034,5.0,8000,200005639,Completed,0.968928
25,FOOD-10384,0,2018-08-06T10:02:43.882903,2163,50400,1472725,5.0,4000,742759541,Completed,0.352108
26,FOOD-10281,0,2018-07-28T12:41:57.633675,1827,55100,357568,5.0,9000,742676336,Completed,0.696736
27,FOOD-10555,0,2018-08-23T19:14:28.409587,1826,34500,1230166,5.0,5000,742616723,Completed,0.794798
28,FOOD-10398,0,2018-08-07T15:17:45.918257,1837,29400,1364703,NaN,16000,742656058,Completed,0.709820
29,FOOD-10731,0,2018-09-08T12:04:40.186645,525,36200,466885,NaN,22000,742731698,Cancelled,0.233675
...,...,...,...,...,...,...,...,...,...,...,...
1046,FOOD-10927,0,2018-09-20T17:48:37.162673,686,33500,532173,5.0,4000,742624919,Completed,0.346230
1047,FOOD-10938,0,2018-09-21T15:41:40.916335,1089,107100,439651,5.0,9000,742537922,Completed,0.634944
1048,FOOD-10431,0,2018-08-11T16:00:41.936249,1797,131200,1220358,3.0,9000,742587112,Completed,0.253443
1049,FOOD-10260,0,2018-07-25T18:44:26.630766,1187,110700,1351793,5.0,4000,742596532,Completed,0.055135
1050,FOOD-10300,0,2018-07-29T19:08:14.623026,1238,31200,316834,5.0,15000,742611439,Completed,0.508601
1051,FOOD-11035,0,2018-09-27T20:38:02.479279,1290,204200,185161,NaN,10000,742526841,Completed,0.147906
1052,FOOD-10756,0,2018-09-09T20:19:34.872483,1655,54000,1383625,NaN,9000,742587499,Completed,0.417650
1053,FOOD-10954,0,2018-09-22T14:10:04.789447,3292,40600,1230166,4.0,10000,742538207,Completed,0.609392
1054,FOOD-10792,0,2018-09-13T18:41:39.521047,2790,111800,1514562,5.0,10000,742677857,Completed,0.368740
1055,FOOD-10557,0,2018-08-23T20:05:47.532186,2914,126200,1150199,5.0,9000,742621820,Completed,0.053234
1056,FOOD-10902,0,2018-09-18T18:47:29.572988,2594,248800,384520,5.0,13000,742531743,Completed,0.864520
1057,FOOD-10957,0,2018-09-22T16:47:13.318708,60,252200,1206592,NaN,13000,742587459,Cancelled,0.726522
1058,FOOD-10994,0,2018-09-24T13:10:44.492311,2146,59200,1096998,NaN,4000,742539982,Completed,0.403036
1059,FOOD-10119,0,2018-07-12T11:18:13.950877,736,56900,304856,NaN,19000,742645951,Cancelled,0.580990
1060,FOOD-10236,5000,2018-07-23T12:43:30.615313,1455,57900,255310,5.0,0,742633392,Completed,0.680000
1061,FOOD-10701,0,2018-09-05T16:06:59.071322,495,83800,594840,5.0,12000,742663766,Completed,0.169563
1062,FOOD-10087,15000,2018-07-09T12:25:52.984375,1430,43700,1284060,5.0,0,742619113,Completed,0.450992
1063,FOOD-10348,0,2018-08-03T19:00:33.367449,1579,54000,1319474,5.0,4000,742685430,Completed,0.080734
1064,FOOD-10079,0,2018-07-08T16:24:18.530533,1246,74000,697545,5.0,9000,742609505,Completed,0.319950
1065,FOOD-10463,0,2018-08-13T19:27:09.707228,1677,67800,1479204,NaN,4000,742645091,Completed,0.289530
1066,FOOD-10074,0,2018-07-08T13:41:27.613831,845,24500,82690,5.0,4000,742720998,Completed,0.312766
1067,FOOD-10393,0,2018-08-07T14:12:19.974028,1909,106900,366721,5.0,9000,742576373,Completed,0.660560
1068,FOOD-10430,0,2018-08-11T15:44:19.426175,1655,80600,366721,5.0,4000,742538793,Completed,0.345022
1069,FOOD-10459,0,2018-08-13T14:24:44.933401,303,17400,1360716,NaN,4000,742620429,Cancelled,0.668113
1070,FOOD-10501,0,2018-08-18T14:27:07.313160,3040,62300,1191779,NaN,14000,742618679,Completed,0.234673
1071,FOOD-10921,0,2018-09-20T15:01:52.152828,900,103200,1296335,5.0,4000,742742150,Completed,0.248328
1072,FOOD-10265,5000,2018-07-26T14:43:23.655294,1579,145700,1135466,5.0,7000,742566851,Completed,0.268251
1073,FOOD-10534,0,2018-08-21T20:10:59.283185,2606,177200,1383625,NaN,15000,742571888,Completed,0.132528
1074,FOOD-10158,0,2018-07-16T14:42:23.214427,2428,49300,1094787,5.0,9000,742725064,Completed,0.167946
1075,FOOD-10770,0,2018-09-11T14:18:19.494258,1547,43000,1010922,5.0,9000,742594499,Completed,0.358051